config/routes.rb
Fandom::Application.routes.draw do

  get "main/index"

  devise_for :users

  get 'users/:id' => 'users#show', :as => :users_path

  root :to => 'main#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :remember_me
  # attr_accessible :title, :body

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fandom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-static-top">
	  <div class="navbar-inner">
	    <div class="container">

	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>

	      <!-- Be sure to leave the brand out there if you want it shown -->
	      <a class="brand active" href="#">Fandom</a>

			<ul class="nav">
				<% if @user %>
					<li class="active"><%= nav_link "Profile", users_path_url(@user.id) %></li>
				<% end %>
				<!-- Need to fill this in after creating Games [DBU 12/30/12] -->
				<li><a href="/games">Games</a></li>
			</ul>

			<ul class="nav secondary">
				<% if user_signed_in? %>
					<li>
				  		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
					</li>
				<% else %>
					<li>
				  		<%= link_to "Sign up", new_user_registration_path %>
					</li>
					<li>
						<%= link_to "Sign in", new_user_session_path %>
					</li>
				<% end %>
			</ul>

	      <!-- Everything you want hidden at 940px or less, place within here -->
	      <div class="nav-collapse collapse">
	        <!-- .nav, .navbar-search, .navbar-form, etc -->
	      </div>

	    </div>
	  </div>
	</div>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>
<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

app/views/users/show.html.erb
<%= @user.first_name %> <%= @user.last_name %>